# Generated by Django 5.2.7 on 2025-11-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_recipe_profit_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='admin_approval',
            new_name='finance_approval',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='manager_approval',
            new_name='operations_manager_approval',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='units',
        ),
        migrations.AddField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.requisition')),
            ],
        ),
    ]
