# Generated by Django 5.2.1 on 2025-09-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='myapp.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Profit percentage for selling price in UGX', max_digits=5),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost in UGX', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit in UGX', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total price in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in UGX', max_digits=10),
        ),
    ]
