# Generated by Django 5.2.7 on 2025-11-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_admin_approval_requisition_finance_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(default='REQ-0001', editable=False, max_length=20, unique=True),
        ),
    ]
