# Generated by Django 5.2.1 on 2025-09-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menuitem_recipe_recipe_profit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity_needed',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Profit percentage for selling price', max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
