# Generated by Django 5.2.7 on 2025-11-05 11:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_requisition_requisition_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Requisition', 'verbose_name_plural': 'Requisitions'},
        ),
        migrations.AddField(
            model_name='requisition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update time'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When requisition was created'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='director_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Director approval status', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='finance_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Finance approval status', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='operations_manager_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Operations Manager approval status', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated: REQ-0001, REQ-0002...', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of all items', max_digits=15),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(help_text='User who created the requisition', on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['requisition_number'], name='myapp_requi_requisi_0a71eb_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['created_at'], name='myapp_requi_created_50654d_idx'),
        ),
    ]
