# Generated by Django 5.2.1 on 2025-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_inventoryhistory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price in UGX', max_digits=10),
        ),
    ]
