# Generated by Django 5.2.1 on 2025-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='order',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for inventory change', max_length=200),
        ),
    ]
