# Generated by Django 5.2.7 on 2025-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_requisition_options_requisition_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated: REQ-0001, REQ-0002...', max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['user'], name='myapp_requi_user_id_c9907f_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.UniqueConstraint(fields=('requisition_number',), name='unique_requisition_number'),
        ),
    ]
