# Generated by Django 5.2.7 on 2025-11-05 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_requisition_requisition_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('submit', 'Submitted')], max_length=20)),
                ('field', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='requisition',
            name='unique_requisition_number',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='myapp_requi_requisi_0a71eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='myapp_requi_created_50654d_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='myapp_requi_user_id_c9907f_idx',
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hide from active list when fully approved'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='director_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='finance_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='operations_manager_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(blank=True, default=7, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisitionhistory',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.requisition'),
        ),
        migrations.AddField(
            model_name='requisitionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
