# Generated by Django 5.2.7 on 2025-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_requisitionhistory_alter_requisition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
