# Generated by Django 5.2.1 on 2025-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_recipe_selling_price_recipe_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in UGX', max_digits=10),
        ),
    ]
