# Generated by Django 5.2.1 on 2025-10-01 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_recipeingredient_total_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='comments',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='inventory_items',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='units',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='change_type',
            field=models.CharField(choices=[('Added', 'Added'), ('Used', 'Used'), ('Adjusted', 'Adjusted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='units',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Desserts', 'Desserts')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='myapp.recipe'),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity_needed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
