# Generated by Django 5.2.7 on 2025-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_requisition_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'requisition_counter',
            },
        ),
    ]
