# Generated by Django 5.2.7 on 2025-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_requisitioncounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitioncounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
