# Generated by Django 5.2.1 on 2025-10-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_comments_requisition_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='description',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='requisition',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=11, help_text='Price per unit in UGX', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
