# Generated by Django 5.2.7 on 2025-11-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_requisitioncounter_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitionhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('operations_manager', 'Operations Manager'), ('finance', 'Finance'), ('director', 'Director')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve to activate'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
