# Generated by Django 5.2.6 on 2025-11-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_requisitionhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='DTable',
        ),
    ]
